# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b4RhQgdtFUD7-ocl25Hodk9L8bM8IsA_
"""

from math import *
import numpy as np
import matplotlib . pyplot as plt
def funcion1(x):
    return np.exp(x) + 2**(-x)+ 2*cos(x)-6
def d1(x):
    return np.exp(x) - (np.log(2)/( 2**(x))) -2*sin(x)
def funcion2(x):
  return np.log( - 2**(-x) -  2*cos(x)+ 6)

# Ingreso datos de entrada para los diferentes métodos a trabajar
a = 1
b = 2
l2=[]
l1=[]
l3=[]
l4=[]
# guarda valores iniciales para bisección
a0 = a
b0 = b

# guarda valores iniciales para Newton
pi=1.1
# guarda valores iniciales para secante
p0=1
p1=1.5
#guarda valores iniciales del error y del número de iteraciones
tol = 0.00001  #float(input("Ingrese el valor de la tolerancia: "))
nmax = 30 #float(input("Ingrese el número máximo de iteraciones: "))
error = 100
e=100
er=100
niter = 1
#Método bisección
m = a + (b - a)/2
fa = funcion1(a)
fb = funcion1(b)
fm = funcion1(m)
while er > tol and niter < nmax:
    m = a + (b - a) / 2
    if np.sign(fa) == np.sign(fm):
        a = m
        fa = funcion1(a)
    else:
        b = m
        fb = funcion1(b)
    
    m = a + (b - a)/2
    fm = funcion1(m)
    er= abs(b - a)
    l3.append(er)
    niter += 1
# Método punto fijo 
it=0
err=100
o=(a0+b0)/2

while err > tol and it <= nmax:
 
  r=funcion2(o)

  err=abs(o-r) 

  l4.append(err)
  o=r
  it += 1


# Método de  Newton

#Evaluacion de la función en los puntos a, b y m

i=1
print("# iter  \t\t P  \t\t error")
print("{0} \t\t {1:6.4f}  \t {2:6.4f}".format(i, pi, error ))

# ciclo iterativo
while error > tol and i <= nmax:
    fa=funcion1(pi)  
    da=d1(pi)
    p = pi - (fa/da)
    error = abs(p - pi)

    pi=p
    l2.append(error)
    i += 1
    print("{0} \t\t {1:6.6f} \t {2:6.6f}".format(i, p,error ))

print("La raíz de la función dada en el intervalo [{0:6.4f},{1:6.4f}] es {2:6.7f}".format(a,b,p))
#Metodo de la secante 
while e > tol and i <= nmax:
   
    fa=funcion1(p0)  
    fb=funcion1(p1)
    pe= p1 - (fb*(p1-p0))/(fb-fa)
    
    e= abs(p1 - p0)
    p0=p1
    p1=pe
    
    i += 1
    l1.append(e)



plt.plot(l1, label="Método de la secante")
plt.plot(l2, label =" Método de Newton")
plt.plot(l3, label ="Método de Bisección ")
plt.plot(l4, label="Método punto fijo")
plt.xlabel("iteraciones")
plt.ylabel("error")
plt.title("Gráfica error vs iteraciones ")
plt.legend()
plt.show()

